export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export  const INITIATE_LOGOUT = 'INITIATE_LOGOUT';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_USER = 'LOGOUT_USER';

export const SET_AUTH_REDIRECT_PATH  = 'SET_AUTH_REDIRECT_PATH'


export const USER_DATA_SUCESS = 'USER_DATA_SUCESS';
export const USER_DATA_START ='USEER_DATA_START';
export const USER_DATA_FAIL = 'USER_DATA_FAIL';

export const FETCH_USERS_START = 'FETCH_USERS_START';
export const FETCH_USERS_SUCESS = 'FERCH_USERS_SUCESS';
export const FETCH_USERS_FAIL = 'FETCH_USERS_FAIL'

export const UPDATE_USER_SUCESS = 'UPDATE_USER_SUCESS';
export const UPDATE_USER_START = 'UPDATE_USER_START';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';

export const DELETE_USER ='DELETE_USER';
export const DELETE_START = 'DELETE_START';

export const FETCH_FAVORITES_START = 'FETCH_FAVORITES_START';
export const FETCH_FAVORITES_SUCCESS ='FETCH_FAVORITES_SUCCESS';
export const FETCH_FAVORITES_FAIL = 'FETCH_FAVORITES_FAIL';

export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_START = 'GET_USER_START'
